"""add grocery fields to item

Revision ID: 342d03577063
Revises: 
Create Date: 2026-03-22 09:39:46.862578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342d03577063'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('checked', sa.Boolean(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('checked')
        batch_op.drop_column('notes')
        batch_op.drop_column('category')
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
